"""modify cart table

Revision ID: 0807a98598c0
Revises: 4c5c4d8f8e8e
Create Date: 2024-12-06 23:19:16.406771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0807a98598c0'
down_revision = '4c5c4d8f8e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'product_url')
    # ### end Alembic commands ###
